#+title: Office Lady
#+author: Office Lady Maker

* Subject

A mature Japanese office lady

** Hair

*** Hair Color

Her hair is black.

*** Highlights

She gets dark brown highlights.

*** Bun

She wears her hair in a low bun.

*** Flyaways

She has a lot of flyaways on her head.

*** Hair Tendrils

She wears hair tendrils.

*** Hair Shine

She has super shiny hair.

** Expression

She has a suggestive expression that ideas are brewing.

** Cup Size

She has a cup size of 34E.

** Skin

She appears to have porcelain skin and rosy cheeks.

** Mouth

She has a definite wide mouth with slim lips.

** Eyes

She highlights her monolid eyes with a touch of thin eyeliner and mascara.

** Freckles

She has freckles.

** Accessories

- She wears a slender silver necklace and a slinky wristwatch.
- She wears a wedding ring on the left ring finger.
- She wears a blue ID card around her neck.

** Shoulders

Her shoulders are delicate.

** Tops

She wears a sleeveless high-neck ribbed sweater.

** Nails

She gets a nude manicure.

** Makeup

*** Pre-makeup Skincare

- She applies one layer of hyaluronic acid toner.
- She applies a moisturizer.
- She applies one layer of sunscreen.

*** Base Makeup

- She uses a brightening concealer.
- She wears a dewy foundation.
- She uses a loose powder.

*** Eyebrow Drawing

- She has thin straight brows.

*** Contour

She uses a taupe contour. It blends out warm.

*** Bronzer

She uses a powder bronzer.

*** Eyeshadow

She uses a eyeshadow primer and a eyeshadow.

*** Aegyo-sal

She has natural aegyo-sal.

*** Curling Eyelashes

She curls her eyelashes.

*** Eyeliner

She does a wing eyeliner.

*** Blush

She gets blushes.

*** Lipstick

She puts on lipstick.

** Figure

Her figure is slender.

* Action

She crosses her arms and tilts her head.

* Enviornment

- in the cramped office
- late at night, darkness filling the windows and interior lights low

* Art Style

A Japanese-style illustration which could be a work on Pixiv or a post on Danbooru.

* Lighting

soft lighting

* Shot Scale

portrait
