#+title: Office Lady
#+author: Office Lady Maker

* Main Content

The main content *must* appear within the frame. The details of the main content should be as rich as possible.

** Expression

seductive, languid

** Cup Size

E-cup

** Breast Shape

round

* Secondary Content

To highlight the main content, the finer details of secondary content can be appropriately trimmed.

** Skin

rosy, glossy

** Lips

thin lips

** Head Pose

tilting head

** Hair Color

dark brown

** Hairstyle

She parts her hair in the middle and ties it back.

** Eye Shape

phoenix eyes

** Facial Pigmentation Spots

freckles

** Accessories

thin silver necklace, petite wristwatch, blue lanyard badge, Wearing a ring on the ring finger of the left hand

** Shoulders

Shoulders are very narrow.

** Figure

slender

** Tops

sleeveless high-neck ribbed knit sweater

** Hand Pose

arms crossed

** Nail

simple nail art

** Nationality

japanese

** Race

yellow race, mongoloid race, east asian people

** Identity

office lady, young married woman

** Time

night

** Location

office

** Art Style

japanese-korean illustration

** Shot Scale

upper body
