#+title: Office Lady
#+author: Office Lady Maker

* Subject

A mature Japanese office lady

** Hair

-  She has naturally black hair. She has been getting chestnut highlights for a long time now.
-  She wears her hair in a low bun. She wears hair tendrils.

** Expression

She has a suggestive expression that ideas are brewing.

** Cup Size

She has a cup size of 32F.

** Skin

She appears to have porcelain skin and rosy cheeks.

** Mouth

She has a definite wide mouth with slim lips.

** Eyes

She highlights her monolid eyes with a touch of thin eyeliner and mascara.

** Freckles

She has freckles.

** Accessories

- She wears a slender silver necklace and a slinky wristwatch.
- She wears a wedding ring on the left ring finger.
- She wears a blue ID card around her neck.

** Shoulders

Her shoulders are delicate.

** Tops

She wears a sleeveless high-neck ribbed sweater.

** Nails

She gets a nude manicure.

* Action

She folds her arms across her chest and cocks her head, sizing up the viewer in front of her.

* Enviornment

in the office after getting off work late at night

* Art Style

japanese-korean illustration

* Lighting

a few lights

* Shot Scale

portrait
