#+title: Office Lady
#+author: Office Lady Maker

* Subject

A mature Japanese office lady

** Hair

-  She has naturally black hair. She has been getting chestnut highlights for a long time now.
-  She wears her hair in a low bun. She wears hair tendrils.

** Expression

She has a suggestive expression that ideas are brewing.

** Cup Size

She has a cup size of 34E.

** Skin

She appears to have porcelain skin and rosy cheeks.

** Mouth

She has a definite wide mouth with slim lips.

** Eyes

She highlights her monolid eyes with a touch of thin eyeliner and mascara.

** Freckles

She has freckles.

** Accessories

- She wears a slender silver necklace and a slinky wristwatch.
- She wears a wedding ring on the left ring finger.
- She wears a blue ID card around her neck.

** Shoulders

Her shoulders are delicate.

** Tops

She wears a sleeveless high-neck ribbed sweater.

** Nails

She gets a nude manicure.

* Action

She crosses her arms and tilts her head.

* Enviornment

- in the cramped office
- late at night, darkness filling the windows and interior lights low

* Art Style

soft shading

* Lighting

soft lighting

* Shot Scale

portrait
