#+title: Office Lady
#+author: Office Lady Maker

* Subject

A mature Japanese office lady

** Hair

-  Her hair color is black with brown highlights.
-  Her hairstyle features a low bun with tendrils.

** Expression

Her expression is suggestive.

** Cup Size

Her cup size is G cup.

** Skin

Her skin is rosy and glowing.

** Lips

Her lips are very thin.

** Eyes

She has a pair of phoenix eyes.

** Freckles

She has freckles on her face.

** Accessories

- She wears a very thin silver necklace and a petite wristwatch.
- She wears a ring on the ring finger of her left hand.
- A blue lanyard work badge hung around her neck.

** Shoulders

Her shoulders are very narrow.

** Tops

She wears a sleeveless high-neck ribbed sweater.

** Nails

She gets a simple manicure and paints her nails light pink.

* Action

She folds her arms across her chest and cocks her head, sizing up the viewer in front of her.

* Enviornment

in the office after getting off work late at night

* Art Style

japanese-korean illustration

* Lighting

a few lights

* Shot Scale

portrait
