#+title: Office Lady
#+author: Office Lady Maker

* Main Content

The main content *must* appear within the frame. The details of the main content should be as rich as possible.

** Subject

A mature Japanese office lady.

*** Hair

-  Her hair is black with brown highlights.
-  She parts her hair in the middle and ties it back.

*** Expression

She had a suggestive gentle expression on her face.

*** Cup Size

She wears an G cup.

*** Skin

Her skin is rosy and glowing.

*** Lips

Her lips are very thin.

*** Eyes

She has a pair of phoenix eyes.

*** Freckles

She has freckles on her face.

*** Accessories

- She wears a very thin silver necklace and a petite wristwatch.
- She wears a ring on the ring finger of her left hand.
- A blue lanyard work badge hung around her neck.

*** Shoulders

Her shoulders are very narrow.

*** Tops

She wears a sleeveless high-neck ribbed sweater.

*** Nails

She gets a simple manicure and paints her nails light pink.

** Action

She folds her arms across her chest and cocks her head, sizing up the viewer in front of her.

** Enviornment

In the office after getting off work late at night.

** Art Style

japanese-korean illustration

** Lighting

a few lights

** Shot Scale

portrait

* Secondary Content

To highlight the main content, the finer details of secondary content can be appropriately trimmed.
